AdmissionCommittee.Web/Models/EntrantsViewModel.cs
using AdmissionCommittee.BL.Contracts.Models;

namespace AdmissionCommittee.Web.Models
{
    public class EntrantsViewModel
    {
        public IReadOnlyCollection<Entrant> Entrants { get; set; } = [];

        public EntrantStatistics? Stats { get; set; } = null;
    }
}

AdmissionCommittee.Web/Models/ErrorViewModel.cs
namespace AdmissionCommittee.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AdmissionCommittee.Web/Controllers/EntrantsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using AdmissionCommittee.Web.Models;
using AdmissionCommittee.BL.Contracts.Models;
using AdmissionCommittee.BL.Contracts;

namespace AdmissionCommittee.Web.Controllers
{
    /// <summary>
    /// Контроллер для работы с абитуриентами
    /// </summary>
    public class EntrantsController : Controller
    {
        private readonly IEntrantManager entrantManager;

        /// <summary>
        /// ctor
        /// </summary>
        public EntrantsController(IEntrantManager entrantManager)
        {
            this.entrantManager = entrantManager;
        }

        /// <summary>
        /// Отображает список абитуриентов
        /// </summary>
        public async Task<IActionResult> Index()
        {
            var entrants = await entrantManager.GetEntrants(CancellationToken.None);
            var stats = await entrantManager.GetEntrantStatistics(CancellationToken.None);

            var viewModel = new EntrantsViewModel
            {
                Entrants = entrants,
                Stats = stats,
            };

            return View(viewModel);
        }

        /// <summary>
        /// Отображает форму для добавления и редактирования
        /// </summary>
        [HttpGet]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return View(new Entrant());
            }

            var entrant = await entrantManager.GetEntrantOrThrowIfNull(id.Value, CancellationToken.None);
            if (entrant == null)
            {
                return NotFound();
            }

            return View(entrant);
        }

        /// <summary>
        /// Обрабатывает форму для добавления и редактирования
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> Edit(Entrant entrant)
        {
            if (ModelState.IsValid)
            {
                if (entrant.Id == Guid.Empty)
                {
                    await entrantManager.Add(new EntrantRequest(
                        entrant.Name,
                        entrant.Gender,
                        entrant.Birthday,
                        entrant.EducationForm,
                        entrant.MathExamScore,
                        entrant.ITExamScore,
                        entrant.RusExamScore),
                        CancellationToken.None);
                }
                else
                {
                    await entrantManager.Edit(entrant.Id,
                        new EntrantRequest(
                        entrant.Name,
                        entrant.Gender,
                        entrant.Birthday,
                        entrant.EducationForm,
                        entrant.MathExamScore,
                        entrant.ITExamScore,
                        entrant.RusExamScore),
                        CancellationToken.None);
                }

                return RedirectToAction("Index");
            }

            return View(entrant);
        }

        /// <summary>
        /// Обработка удаления
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> Delete(Guid id)
        {
            await entrantManager.Delete(id, CancellationToken.None);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AdmissionCommittee.Web/Views/Entrants/Edit.cshtml
@using AdmissionCommittee.BL.Contracts.Models
@model Entrant;

@{
    ViewBag.Title = Model.Id != Guid.Empty ? "Редактировать абитуриента" : "Добавить абитуриента";
}

<h2>@ViewBag.Title</h2>

<div class="row justify-content-center">
    <form method="post" class="col-auto justify-content-end" style="text-align: center">
        <input type="text" asp-for="Id" readonly hidden />
        <p>
            @Html.LabelFor(model => model.Name)
            @Html.EditorFor(model => model.Name)<br />
            <span asp-validation-for="Name"></span>
        </p>
        <p>
            @Html.LabelFor(model => model.Birthday)
            <input type="date" asp-for="Birthday" /><br />
            <span asp-validation-for="Birthday"></span>
        </p>
        <p>
            @Html.LabelFor(model => model.Gender)
            @Html.DropDownListFor(model => model.Gender, Html.GetEnumSelectList<Gender>())
        </p>
        <p>
            @Html.LabelFor(model => model.EducationForm)
            @Html.DropDownListFor(model => model.EducationForm, Html.GetEnumSelectList<EducationForm>())
        </p>
        <p>
            @Html.LabelFor(model => model.ITExamScore)
            @Html.EditorFor(model => model.ITExamScore)<br />
            <span asp-validation-for="ITExamScore"></span>
        </p>
        <p>
            @Html.LabelFor(model => model.MathExamScore)
            @Html.EditorFor(model => model.MathExamScore)<br />
            <span asp-validation-for="MathExamScore"></span>
        </p>
        <p>
            @Html.LabelFor(model => model.RusExamScore)
            @Html.EditorFor(model => model.RusExamScore)<br />
            <span asp-validation-for="RusExamScore"></span>
        </p>
        <p>
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </p>
    </form>
</div>

<div>
    <a href="@Url.Action("Index", "Entrants")">Назад к списку</a>
</div>

@section Scripts {
     <partial name="_ValidationScriptsPartial" />
}

AdmissionCommittee.Web/Views/Entrants/Index.cshtml
@model AdmissionCommittee.Web.Models.EntrantsViewModel

@{
    ViewBag.Title = "Список абитуриентов";
}

<h1>Список абитуриентов</h1>

<p>
    <a asp-action="Edit" class="btn btn-success">Добавить абитуриента</a>
</p>

<strong>Общее количество абитуриентов:</strong> @Model.Stats.EntrantsCount
<br />
<strong>Количество абитуриентов с суммой баллов больше 150:</strong> @Model.Stats.EntrantsPassedCount

<table class="table table-striped">
    <thead>
        <tr>
            <th>Имя</th>
            <th>Пол</th>
            <th>Дата рождения</th>
            <th>Форма обучения</th>
            <th>Математика</th>
            <th>Русский</th>
            <th>Информатика</th>
            <th>Сумма баллов</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var entrant in Model.Entrants)
        {
            <tr>
                <td>@Html.DisplayFor(_ => entrant.Name)</td>
                <td>@Html.DisplayFor(_ => entrant.Gender)</td>
                <td>@entrant.Birthday.ToString("dd.MM.yyyy")</td>
                <td>@Html.DisplayFor(_ => entrant.EducationForm)</td>
                <td>@Html.DisplayFor(_ => entrant.MathExamScore)</td>
                <td>@Html.DisplayFor(_ => entrant.RusExamScore)</td>
                <td>@Html.DisplayFor(_ => entrant.ITExamScore)</td>
                <td>@(entrant.MathExamScore + entrant.RusExamScore + entrant.ITExamScore)</td>
                <td>
                    <a class="btn btn-warning btn-sm" href="@Url.Action("Edit", "Entrants", new { id = entrant.Id })">Редактировать</a>
                    <form asp-action="Delete" asp-route-id="@entrant.Id" method="post" style="display:inline;">
                        <button type="submit" class="btn btn-danger btn-sm">Удалить</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

AdmissionCommittee.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdmissionCommittee.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdmissionCommittee.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>